### ISSUE TITLE
[bug] Cannot install @node-lightning/secp256k1 due to preinstall script

### ISSUE THREAD

**Issue by dillionverma** [altangent/node-lightning#237]
I am trying to build a node project with `@node-lightning/secp256k1` as a dependency and running into the following issue:

```
 => [dlcd base 5/7] RUN yarn install --frozen-lockfile --verbose                                       273.3s
 => => # Exit code: 128
 => => # Command: git submodule update --init
 => => # Arguments:
 => => # Directory: /usr/src/dlcd/node_modules/@node-lightning/secp256k1
 => => # Output:
 => => # fatal: not a git repository (or any of the parent directories): .git
```

Looking into the code, it seems like [this line here](https://github.com/altangent/node-lightning/blob/main/packages/secp256k1/package.json#L11) is the culprit. The preinstall hook calls `git submodule init` but it fails since packages in node_modules aren't version controlled and don't contain `.git/` in them.

Can we remove the preinstall hook and instead write instructions to call `git submodule update --init` once during the creation of the project? Seems like `git submodule update --init` is related to development of the package and not the production use of it.

**Comment by bmancini55** [comment]
Sorry for the delay.  

That command fetches the submodule `libsecp256k1`.  This module is required in the `postinstall` script when node-gyp is run to compile the module.  In order the `preinstall` script to work your project needs to be in a git repository.  So in your project root, try running `git init` and then installing `@node-lightning/secp256k1` again and it should work.

BTW, this project directly compiles using node-gyp instead of using prebuildify and node-gyp-build.  I'm not the most familiar with node-gyp workflows but this seemed the most direct way to get things working without relying on third party modules.

**Comment by bmancini55** [comment]
This should be resolve in v0.28.0, the git prebuild dependency was removed. I will close the issue for now, but feel free reopen if there is still an issue.
